#!/bin/sh

# multiheadsh - Sets up multihead on i3 on my w540 docked setup

[ "$XDG_SESSION_TYPE" = "x11" ] && xrandr --output eDP1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP1 --off --output DP2 --off --output DP2-1 --off --output DP2-2 --mode 1680x1050 --pos 3840x0 --rotate left --output DP2-3 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI1 --off --output HDMI2 --off --output VGA1 --off --output VIRTUAL1 --off

# xrandr --output eDP1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP1 --off --output DP2 --off --output DP2-1 --off --output DP2-2 --mode 1680x1050 --pos 3840x0 --rotate left --output DP2-3 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI1 --off --output HDMI2 --off --output VGA1 --off --output VIRTUAL1 --off
